name: Scheduled Job

on:  
  schedule:  
    - cron: "0 6 * * *" # 9 утра каждый день

env:
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
  TELEGRAM_CHANNEL_ID: ${{ secrets.TELEGRAM_CHANNEL_ID }}

jobs:
  Daily-Run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2  # Используем стабильную версию v2
      
      - name: Install Dependencies
        run: pip install -r requirements.txt 
      
      - name: Run App
        run: python app.py
