name: Scheduled Job

on:
  schedule:
    - cron: '35 19 16 9 *'  # Запуск в 19:33 по UTC, 16 сентября

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run a script or command
      run: echo "Scheduled Job Executed at 19:33 UTC"
